SET DB_CLOSE_DELAY -1;

CREATE USER IF NOT EXISTS GUEST PASSWORD 'guest';

CREATE TABLE "T" (
  "ID" BIGINT AUTO_INCREMENT PRIMARY KEY,
  "F" INTEGER
);

GRANT ALL ON "T" TO GUEST;

INSERT INTO "T" ("F")
VALUES
(100000),
(200000),
(300000);
