SET DB_CLOSE_DELAY -1;

CREATE USER IF NOT EXISTS GUEST PASSWORD 'guest';

CREATE TABLE "PLACES" (
  "ID" BIGINT AUTO_INCREMENT,
  "NAME" VARCHAR,
  "LIKED" BOOLEAN,
  PRIMARY KEY ("ID")
);

GRANT ALL ON "PLACES" TO GUEST;

-- 3 rows
INSERT INTO "PLACES" ("NAME", "LIKED")
VALUES
('Tempest', TRUE),
('Bullit', TRUE),
('The Dentist', FALSE);
